apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devtinder
  labels:
    app: devtinder-backend
spec:
  selector:
    app: devtinder-backend
  ports:
  - name: nginx
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP