apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devtinder
  labels:
    app: devtinder-frontend
  
spec:
  selector:
    app: devtinder-frontend
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
