apiVersion: v1
kind: ServiceAccount
metadata:
  name: devtinder-sa
  namespace: devtinder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devtinder-role
  namespace: devtinder
rules:
# Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Pod Logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

# ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

# Secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

# Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devtinder-rolebinding
  namespace: devtinder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devtinder-role
subjects:
- kind: ServiceAccount
  name: devtinder-sa
  namespace: devtinder